#include <stdio.h>
#include <string.h>
#include <time.h>
#include <sys/types.h>
#include <rpc/rpc.h> /* standard RPC include file */
#include "date.h"    /* this file is generated by rpcgen */
#include <malloc.h>

#define MAX_LEN 100
long get_response(void);
void memory_stats(CLIENT *clnt);
void cpu_stats(CLIENT *clnt);
void load_average(CLIENT *clnt);
static char errMessage[] = "Some error occurred! \0";

long get_response()
{
    long choice;

    printf("===========================================\n");
    printf("                   Menu: \n");
    printf("-------------------------------------------\n");
    printf("                1. Date\n");
    printf("                2. Time\n");
    printf("                3. Date and Time\n");
    printf("                4. Memory Usage\n");
    printf("                5. CPU Usage\n");
    printf("                6. User List\n");
    printf("                7. Load procs per minute\n");
    printf("                8. Quit\n");
    printf("-------------------------------------------\n");
    printf("               Choice (1-6):");
    scanf("%ld", &choice);
    printf("===========================================\n");
    return (choice);
}
void load_average(CLIENT *clnt)
{
    char **loadAvg;
    if ((loadAvg = load_1(NULL, clnt)) == NULL)
    {
        printf("%s \n", errMessage);
        return;
    }
    printf("Load averages for the past 1, 5, and 15 minutes: %s\n", *loadAvg);
}
void memory_stats(CLIENT *clnt)
{
    char **sresult;
    char **sresult2;
    if ((sresult = memory_1(NULL, clnt)) == NULL)
    {
        printf("%s \n", errMessage);
        return;
    }
    printf("RAM Usage: \n\n");
    printf("%s\n\n", *sresult);

    if ((sresult2 = dynamicmemoryinfo_1(NULL, clnt)) == NULL)
    {
        printf("%s \n", errMessage);
        return;
    }

    int num_values = 4;
    int i = 0;
    printf("Dynamic Memory Usage: \n\n");
    printf("%s\n", *sresult2);
}

void cpu_stats(CLIENT *clnt)
{
    double *sresult;
    if ((sresult = cpu_1(NULL, clnt)) == NULL)
    {
        printf("%s \n", errMessage);
        return;
    }
    printf("CPU usage precentage: %lf %% \n\n", *sresult);
}

void user_list(CLIENT *clnt)
{
    char **sresult;
    if ((sresult = user_1(NULL, clnt)) == NULL)
    {
        printf("%s \n", errMessage);
        return;
    }
    printf("  %s\n", *sresult);
}

main(int argc, char **argv)
{
    CLIENT *cl; /* RPC handle */
    char *server;
    char **sresult;  /* return value from date_1()      */
    char s[MAX_LEN]; /* character array to hold output */
    long response;   /* user response                           */
    long *lresult;   /* pointer to user response          */

    if (argc != 2)
    {
        fprintf(stderr, "usage: %s hostname\n", argv[0]);
        exit(1);
    }
    server = argv[1];
    lresult = (&response);
    /*
     * Create the client "handle."
     */
    if ((cl = clnt_create(server, DATE_PROG, DATE_VERS, "udp")) == NULL)
    {
        clnt_pcreateerror(server);
        exit(2);
    }
    response = get_response();
    while (response != 8)
    {
        if (response == 1 || response == 2 || response == 3)
        {
            if ((sresult = date_1(lresult, cl)) == NULL)
            {
                clnt_perror(cl, server);
                exit(3);
            }
            printf("  %s\n", *sresult);
        }
        else if (response == 4)
        {
            memory_stats(cl);
        }
        else if (response == 5)
        {
            cpu_stats(cl);
        }
        else if (response == 6)
        {
            user_list(cl);
        }
        else if (response == 7)
        {
            load_average(cl);
        }
        else
        {
            printf("Wrong Command! Try Again.\n");
        }
        response = get_response();
    }
    clnt_destroy(cl); /* done with the handle */
    exit(0);
}
